#!/bin/bash

PUID=${PUID:-999}
PGID=${PGID:-$PUID}

usermod -o -u "$PUID" user
groupmod -o -g "$PGID" user
passwd user <<EOF
.
.
EOF

echo "function jack_server() {" >> /etc/bash.bashrc
echo "    if [ \"\$1\" == \"restart\" ]; then" >> /etc/bash.bashrc
echo "        /mnt/out/host/linux-x86/bin/jack-admin kill-server && /mnt/out/host/linux-x86/bin/jack-admin start-server" >> /etc/bash.bashrc
echo "    else" >> /etc/bash.bashrc
echo "        export JACK_SERVER_VM_ARGUMENTS=\"-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx\$1\"" >> /etc/bash.bashrc
echo "    fi" >> /etc/bash.bashrc
echo "}" >> /etc/bash.bashrc


if [ "$JDK" == 7 ]; then
    jdk 7 > /dev/null
else
    jdk 8 > /dev/null
fi
su user
